a = input('Digite algo: ')
print('O tipo primitivo da variável é', type(a))
print('Contém apenas números?', a.isnumeric())
print('Contém apenas letras?', a.isalpha())
print('Contém apenas números e letras?', a.isalnum())
print('Está tudo em maiúsculo?', a.isupper())
print('Está tudo em minúsculo?', a.islower())
print('Está capitalizada?', a.istitle())
print('É um espaço?', a.isspace())
