a = input('Digite algo: ')
print('O tipo primitivo da variável é {}'.format(type(a)))
print('É número? {}'.format(a.isnumeric()))
print('É palavra? {}'.format(a.isalpha()))
print('É alfanumérico? {}'.format(a.isalnum()))
print('É espaço? {}'.format(a.isspace()))
print('É maiúsculo? {}'.format(a.isupper()))
print('É minúsculo? {}'.format(a.islower()))
print('É capitalizada? {}'.format(a.istitle()))
